version: "3.9"
services:
  doorbell-ai-ha:
    container_name: doorbell-ai-ha
    restart: unless-stopped
    build: .
    pull_policy: build
    privileged: true
    group_add:
      - "audio"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/snd:/dev/snd
    environment:
      - HOMEASSISTANT_URL=${HOMEASSISTANT_URL}
      - HOMEASSISTANT_INTERCOM_RING_WEBHOOK_ID=${HOMEASSISTANT_INTERCOM_RING_WEBHOOK_ID}
      - MIC_NAME=${MIC_NAME}
    labels:
      - com.centurylinklabs.watchtower.enable=false
