version: "3.9"
services:
  doorbell-ai-ha:
    container_name: doorbell-ai-ha
    restart: unless-stopped
    build: .
    pull_policy: build
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - HOMEASSISTANT_URL=${HOMEASSISTANT_URL}
      - HOMEASSISTANT_INTERCOM_RING_WEBHOOK_ID=${HOMEASSISTANT_INTERCOM_RING_WEBHOOK_ID}
      - MIC_HW_ID=${MIC_HW_ID}
